### PR TITLE
Setup Webpack, Setup VueJS, Setup TailwindCSS, Create Contact Page

### PR DESCRIPTION
**Pull request by jacobduncan00**

### CODE REVIEW

**Review by jtanderson — COMMENTED** [review]
I see the `package-lock.json` was removed from git tracking, but in fact it's intended to be under source-control for cross-environment consistency (c.f. https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json).

**Comment by jtanderson** [comment]
@Blaine-Mason can you and/or another group member verify that this patch has been tested and working to render and provide each of the pages mentioned? Just a short QA for sanity.

**Comment by jventura1738** [comment]
> @Blaine-Mason can you and/or another group member verify that this patch has been tested and working to render and provide each of the pages mentioned? Just a short QA for sanity.

@jacobduncan00 and I tested the front and backend together and it rendered correctly.

**Comment by Blaine-Mason** [comment]
> @Blaine-Mason can you and/or another group member verify that this patch has been tested and working to render and provide each of the pages mentioned? Just a short QA for sanity.

Tested and works, ready for merge.  Note: Must run "npm install" then "npm run dev" in a separate terminal on the first run.

**Comment by jtanderson** [comment]
Great, @jacobduncan00 let's just get the `package-lock.json` back in there!

**Pull request merged**
