### PR TITLE
Create route to get star status of listing

### PR DESCRIPTION
**Pull request by jventura1738**
For @jacobduncan to use in his star listing fix.

### CODE REVIEW

**Comment by jventura1738** [comment]
@jtanderson this was tested essentially via PR#56 as this feature was used in it.

**Comment by jacobduncan00** [comment]
Good to go, used in my branch

**Comment by jtanderson** [comment]
Is this route really necessary? Shouldn't one simply use the `get-listing` route (which should incidentally probably be just `/listing/<id>`) ?

**Comment by jventura1738** [comment]
> Is this route really necessary? Shouldn't one simply use the `get-listing` route (which should incidentally probably be just `/listing/<id>`) ?

@jacobduncan00  needed it for #56.  Any comment @jacobduncan00 ?

**Comment by jacobduncan00** [comment]
Jacob == Dumb

**Pull request closed without merging**
