### PR TITLE
Admin Listing Backend (PLEASE READ)

### PR DESCRIPTION
**Pull request by jventura1738**
1.  I tested myself, and it works.
2. I need someone else to test:
    a. You will need to seed data yourself to test.
    b. Seeders are outdated, so you may need a temporary seeder (which is what I did)
    c. If you want a copy of my temporary seeder, message me.
3. The main changes to this are for the admin to request the inactive, active, pending, rejected listings.
4. I also forced users to be admins to get access to admin routes.
5. The model has changed significantly, so keep this in mind.

### CODE REVIEW

**Comment by jventura1738** [comment]
Use my testing seeder on your machine

**Comment by jacobduncan00** [comment]
I approve this PR and can confirm that the following code works as it should. When running this branch, you will need to only run the TestingSeeder seeder (I did this by deleting the other seeders) as the other Seeders are outdated and will cause the ```flask seed run``` to error out. However, besides that the functionality of this PR is good to go!

**Comment by jacobduncan00** [comment]
After looking back at the get-listings route in admin.py, I would change the function name attached to that route from 'pending_listings' to 'fetch_listings' or something not specific to pending listings

**Comment by jacobduncan00** [comment]
This also might be a nitpick but any chance you can send me these listings in a 'list of dicts' in python terminology or 'array of objects' in javascript terminology, would be easier for me to parse

**Comment by jventura1738** [comment]
> After looking back at the get-listings route in admin.py, I would change the function name attached to that route from 'pending_listings' to 'fetch_listings' or something not specific to pending listings

Changed to "get_listings", that was my mistake.

**Pull request merged**
