### PR TITLE
Star Listing

### PR DESCRIPTION
**Pull request by jacobduncan00**
Go to /admin/listings
Star or Unstar listing
Reload page and see that it persists

@jventura1738 plz test

### CODE REVIEW

**Review by jventura1738 — APPROVED** [review]
Tested and all good to go! @jtanderson

**Review by jventura1738 — APPROVED** [review]
NOTE: api changes are indeed in sync with star-listing-backend PR

**Comment by jtanderson** [comment]
See comments for star listing backend, #40 and let's address those before merging this. If agreeable, we can open an issue for those changes to happen later and merge these two as-is.

**Comment by jtanderson** [comment]
@jacobduncan00 Make sure this is compatible with PUT method as introduced by #40

**Comment by jacobduncan00** [comment]
@jtanderson fixed branch to work with PUT request and reparsed data sent to me

**Comment by jventura1738** [comment]
@jtanderson Tested and ready for merge.

**Pull request merged**
