### PR TITLE
Admin refactor

### PR DESCRIPTION
**Pull request by jventura1738**
- Refactor admin routes
- > NOTE TO JAKE: get-listings route needs new parse method; check documentation
- Create helper function to validate admin sessions

### CODE REVIEW

**Comment by jtanderson** [comment]
To elaborate on this: the `if`-statement on the admin routes should be completely unnecessary via route hooks (e.g. https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.before_request). This hook can run on every request and, if it's an admin request, check to see that the user is logged in and redirect them if not. That way, the other admin routes can completely assume the requesting user is valid.

**Comment by jventura1738** [comment]
> To elaborate on this: the `if`-statement on the admin routes should be completely unnecessary via route hooks (e.g. https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.before_request). This hook can run on every request and, if it's an admin request, check to see that the user is logged in and redirect them if not. That way, the other admin routes can completely assume the requesting user is valid.

Done.  Please review @jtanderson, and also need someone to perform testing.

**Comment by jventura1738** [comment]
NOTE: until @jacobduncan00 updates the parsing of listings, the admin listings page is "broken," but don't take that into account for this PR's tests.  See 
commit ae470058332e639fd8e2f52900ab23614139433b

**Comment by jtanderson** [comment]
> > To elaborate on this: the `if`-statement on the admin routes should be completely unnecessary via route hooks (e.g. https://flask.palletsprojects.com/en/2.0.x/api/#flask.Flask.before_request). This hook can run on every request and, if it's an admin request, check to see that the user is logged in and redirect them if not. That way, the other admin routes can completely assume the requesting user is valid.
> 
> Done. Please review @jtanderson, and also need someone to perform testing.

@Blaine-Mason feel free to assign this to somebody

Important testing cases:
- Test both admin and non-admin pages
- Test each of above while logged in and not logged in

**Comment by jacobduncan00** [comment]
@jtanderson tested and good to go, implemented justins changes in this PR into my PR in order to fix the issues and everything works seemlessly

**Comment by jacobduncan00** [comment]
@jtanderson justin implemented the @before.request decorator as well like you asked already in this PR

**Pull request merged**
