### PR TITLE
Vue 3 Upgrade & Edit Listing Functionality & Homepage Redesign

### PR DESCRIPTION
**Pull request by jacobduncan00**
See /admin to find a pending listing module, there will be a button called edit which will take you to the edit page for the specified listing. I also plan to add an icon on the listing card in the near future in order to get to this page as well.

### CODE REVIEW

**Comment by jventura1738** [comment]
**One major issue**:  General inconsistencies in starring functionality for listings.  In admin listings view, starring listing_i while in a filter ≠ 'all', then moving to another filter ≠ 'all' will not save the star effect on listing_i.

**One minor issue**:  Odd number listings in admin listing view makes styling weird (last card too wide).

NOTE: @jacobduncan00 knows how to fix this, he will be working on this soon.

**Comment by jacobduncan00** [comment]
Fixed star issue
Fixed styling issue. Still broken on smaller screens, minor issue, will fix later

Good to merge after @jventura1738 tests again

**Review by jventura1738 — APPROVED** [review]
Looks good, will test soon.

**Review by jventura1738 — APPROVED** [review]
Tested and good to go.  @jtanderson

**Pull request merged**
