### PR TITLE
Update Admin Dashboard | Create Admin Listing View | Add Session Timeout

### PR DESCRIPTION
**Pull request by jacobduncan00**
Session timeout set to 30 minutes as seen in api/__init__.py line 48

Added new navbar to admin dashboard see on /admin route

Added listings to navbar and created seperate view for listings /admin/listings

This PR includes Justin's changes as well, hope his code gets merged 💀

### CODE REVIEW

**Comment by jventura1738** [comment]
Features tested and operational as far as I saw.  @jtanderson

**Comment by jacobduncan00** [comment]
Resolved merge conflicts

**Comment by jtanderson** [comment]
@jventura1738 Test with conflict resolution and report back, please!

**Comment by jventura1738** [comment]
Jacob is tested and ready to go @jtanderson !

**Pull request merged**
