### PR TITLE
Edit listing backend

### PR DESCRIPTION
**Pull request by jventura1738**
NOTE TO JACOB @jacobduncan00: Insert listing form is broken as it needs a duration, application open, and application close field now.  Let me know if this should be handled differently.

Tested using Thunder Client VSCode extension for PUT request.

### CODE REVIEW

**Comment by jtanderson** [comment]
@Blaine-Mason assign for test/review

**Comment by jventura1738** [comment]
Fixed issue found by @jacobduncan00; see commit 61c1de2

**Comment by jacobduncan00** [comment]
@jtanderson tested and good to do, currently in process of developing front-end changes for this. Will be included in my next PR

**Review by jacobduncan00 — APPROVED** [review]

**Comment by jventura1738** [comment]
> NOTE TO JACOB @jacobduncan00: Insert listing form is broken as it needs a duration, application open, and application close field now. Let me know if this should be handled differently.
> 
> Tested using Thunder Client VSCode extension for PUT request.

Jacob should have this covered in his next PR

**Pull request merged**
